// Master card list — bundled into the client since there is no server.
// Note: any player can technically inspect this in devtools; true hidden
// information is not achievable without a trusted server. This keeps the
// deck out of the *rendered UI* only — each player still just sees their
// own dealt hand and the shared board.
export const MASTER_DECK = [
  "pocket jerky", "man glitter", "gravy tuxedo", "emotional lasagna",
  "backup mustache", "car jerky", "beef curtains", "moon jerky",
  "wizard chili", "goblin taxes", "raccoon dues", "thunder cape",
  "casserole diplomacy", "jerky negotiations", "mall wizardry", "elevator karaoke",
  "confetti insurance", "yard sale karma", "foot massage voucher", "gym membership curse",
  "carpool prophecy", "birthday cake tax", "lawn gnome census", "thermostat conspiracy",
  "printer mood swings", "storm cellar confidence", "umbrella confidence", "competitive lawn mowing",
  "weather psychic retirement", "karaoke feud", "book club initiation", "glitter shipment",
  "miracle insurance", "ghost tour receipt", "yard sale empire", "confetti cult",
  "nap schedule union", "snack thief apology", "team-building grudge", "thermostat war",
  "secret Santa diplomacy", "motivational poster refund", "vending machine curse", "tax audit karma",
  "parking validation stamp", "jury duty excuse", "HOA newsletter cult", "cryptid census",
  "mustache retirement plan", "fanny pack emergency", "sock drawer hierarchy", "garden gnome census",
  "lawn mower feud", "traffic cone loyalty", "mailbox curse", "glove compartment receipts",
  "exorcist side hustle", "fortune cookie fortune", "cereal mascot comeback", "mall Santa tell-all",
  "karaoke machine curse", "thunder cape rental", "apocalypse coupon", "time machine warranty",
  "séance Groupon", "cryptid discount card", "weather forecast leak", "umbrella surplus",
  "gnome union rep", "stapler loyalty program", "birthday cake mixup", "spice rack alphabetization",
  "gas station sushi confidence", "airline peanut nostalgia", "donut integrity", "good scissors mystery",
  "missing silverware", "expired coupon guilt", "mystery Tupperware", "cake with wrong name",
  "golden retriever alibi", "clown union dues", "mime confession", "tooth fairy debt",
  "orange peel superstition", "whistling suspicion", "raccoon felony record", "morning person deflection",
  "ironed jeans confidence", "umbrella stockpile", "weather forecaster credibility", "plane clap etiquette",
  "office cryptid theory", "chef taste-test rule", "dog bark instinct", "unofficial mayor election",
  "unlabeled key mystery", "horse-eating hyperbole", "family spy theory", "barista name error",
  "drinks-sometime promise", "hotel pillow standards", "jigsaw puzzle guilt", "llama connection",
  "neighborhood maze incident", "houseplant naming ceremony", "gas station bathroom ranking", "cereal company complaint letter",
  "favorite traffic cone", "parking lot nap", "vending machine negotiation", "junk drawer vibe system",
  "mannequin mistaken identity", "spare umbrella generosity", "handwriting distrust", "parallel parking ovation",
  "discontinued ranch flavor", "pickle toothpaste", "bacon candle scent", "gluten-free thoughts and prayers",
  "expired fortune cookie wisdom", "secret sauce theft", "last known good donut", "backup weatherman",
  "backup mayor inauguration", "loyalty point dispute", "tax return theatrics", "retirement casserole",
  "office birthday tax collector", "printer retirement plan", "nap union dispute", "snack thief manifesto",
  "karaoke song monopoly", "confetti tax audit", "yard sale conglomerate", "thermostat truce negotiations",
  "fortune teller Yelp review", "band greatest hits reunion", "secret Santa oversaturation", "mayor inauguration snacks",
  "miracle return policy", "DMV reschedule saga", "ghost accountant advice", "small talk cousin theory",
  "truck nobody talks about", "thunder cape rental dispute", "motivational poster typo", "shuttle retirement plan",
  "loyalty point refund request", "nap schedule dispute", "cereal mascot comeback tour", "discount card scandal",
  "garden gnome sponsorship", "parking validation cousin", "cake tax collector shift", "I don't trust people who eat candy corn",
  "I don't trust people who fold their pizza", "nobody who owns a golden retriever is capable of real evil", "I refuse to trust anyone who says 'no offense' before being offensive", "people who talk during movies are secretly lizards",
  "I've never met a mime I didn't suspect of something", "anyone who microwaves fish at the office should register as a felon", "I think clowns unionized decades ago and nobody noticed", "I don't believe anyone who says they don't really watch TV",
  "I've always suspected the tooth fairy has a gambling problem", "I don't trust anyone who peels an orange in one piece", "nobody who whistles in public has been fully honest with a therapist", "I think every raccoon has committed at least one felony",
  "anyone who says they're not a morning person is hiding something bigger", "I've never trusted a man who irons his jeans", "people who own three or more umbrellas are planning something", "I don't believe weather forecasters have ever been outside",
  "nobody who claps when the plane lands has read the safety card", "I think every office has one person who's secretly a cryptid", "I refuse to trust a chef who doesn't taste their own food", "I don't trust a dog that doesn't bark at the mailman",
  "people who alphabetize their spice rack are hiding something", "I think every small town has one unofficial mayor nobody elected", "I've never trusted a man who owns a single unlabeled key", "nobody who says they could eat a horse has thought that through",
  "I think every family has one relative who might be a spy", "I don't trust a barista who doesn't get my name wrong", "anyone who says we should get drinks sometime rarely means it", "I think every hotel pillow is secretly the same pillow",
  "I've never finished a jigsaw puzzle and I'm not ashamed", "I think every gas station has exactly one honest bathroom", "I don't trust anyone who says they love public speaking", "nobody who owns a fog machine has ever used it responsibly",
  "I think every family reunion has one unresolved conspiracy", "I've never trusted a cat that makes eye contact too long", "anyone who irons their socks is planning a coup", "I think every school had one kid who might've been an adult",
  "I don't trust anyone who says the wifi password out loud twice", "nobody who owns matching luggage has ever missed a flight", "I think every neighborhood has one dog running the whole block", "deep fried Twinkie",
  "slippery when wet", "still warm", "extra saucy", "handle with care",
  "goes down smooth", "comes in a family pack", "bigger on the inside", "hard to swallow",
  "better with two hands", "size doesn't matter", "made fresh daily", "worth the wait",
  "hits different at 2am", "not as sticky as it looks", "needs a firm grip", "best served warm",
  "loosens up after a minute", "takes two tries", "leaves a mark", "smells better than it looks",
  "gets better the longer you wait", "sturdier than it looks", "runs hot", "double-wrapped for a reason",
  "doesn't taste like much at first", "goes further than you'd think", "easier the second time", "leaves you sticky",
  "comes with instructions for a reason", "tighter than expected", "softer in the morning", "needs to breathe first",
  "better on the second date", "comes pre-shaken", "tastes like a bad decision", "looks small in the package",
  "needs a warning label", "goes in easier sideways", "lasts longer refrigerated", "I once won a hot dog eating contest by accident",
  "my emotional support animal is a lawn chair", "I've been banned from exactly one Chuck E. Cheese", "I have a whole system for microwave popcorn timing", "I know a guy who knows a guy who owns a llama",
  "I once got lost in my own neighborhood for forty minutes", "I've named every houseplant I've ever killed", "I have strong opinions about hotel pillows", "I once tried to return a fish I caught myself",
  "I keep a mental ranking of every gas station bathroom I've used", "I've written a strongly worded letter to a cereal company", "I have a favorite traffic cone", "I've fallen asleep in a grocery store parking lot on purpose",
  "I once negotiated with a vending machine for twenty minutes", "I have a system for organizing junk drawers by vibe", "I've been mistaken for a mannequin at least once", "I keep a spare umbrella specifically for other people's emergencies",
  "I've never trusted my own handwriting on important forms", "I once got a standing ovation for parallel parking", "I've read a hotel's fire safety card cover to cover for fun", "I once cried during a car commercial and won't explain why",
  "I have a nemesis at the DMV and she doesn't know it", "I've practiced a fake laugh in the mirror", "I once applauded during a fire drill", "I keep receipts I don't need just in case",
  "I've had a staring contest with a goose and lost", "I once wore sunglasses indoors to avoid a conversation", "I have a backup nickname I've never used", "I've rehearsed an argument with someone who wasn't there",
  "I once said 'you too' when a waiter told me to enjoy my meal", "discount time travel", "emergency backup soul", "unlicensed guardian angel",
  "expired gym membership guilt", "secondhand thunder", "borrowed confidence", "refurbished bravado",
  "clearance rack destiny", "factory-reset karma", "last-minute miracle", "overnight prophecy",
  "rush-order redemption", "gift-wrapped apology", "hand-me-down superstition", "bootleg enlightenment",
  "knockoff nirvana", "pop-up shrine", "flash-sale forgiveness", "limited-edition guilt trip",
  "seasonal existential crisis", "buy-one-get-one regret", "store-brand serenity", "off-peak enlightenment",
  "layaway redemption arc", "self-checkout confession", "curbside epiphany", "drive-thru wisdom",
  "fast-track forgiveness", "backorder destiny", "overstock nostalgia", "clearance-bin bravery",
  "bulk-size humility", "trial-size confidence", "free-sample loyalty", "warranty-void honesty"
];

export const HAND_SIZE = 5;
