// Master card list — bundled into the client since there is no server.
// Note: any player can technically inspect this in devtools; true hidden
// information is not achievable without a trusted server. This keeps the
// deck out of the *rendered UI* only — each player still just sees their
// own dealt hand and the shared board.
export const MASTER_DECK = [
  "pocket jerky", "man glitter", "moist handshake", "gravy tuxedo",
  "backyard wizard", "discount vampire", "emotional casserole", "haunted fanny pack",
  "crunchy diplomacy", "the sock drawer treaty", "unlicensed cowboy", "spicy grandma",
  "a suspicious number of spoons", "off-brand thunder", "gluten-free werewolf",
  "the raccoon's lawyer", "squeaky democracy", "a two-for-one soul", "cursed tupperware",
  "the mayor of nothing", "beef jerky feelings", "a rental mustache", "sarcastic oatmeal",
  "the ghost of Tuesday", "damp enthusiasm", "an unpaid intern for Satan", "spare kneecap",
  "the sock puppet uprising", "a knockoff soulmate", "expired confidence", "gravy diplomacy",
  "the neighborhood's secret handshake", "a suspiciously calm goose", "backup thumbs",
  "the last known unicorn", "a discount séance", "leftover mystery meat", "grandma's other wig",
  "a part-time cryptid", "the raccoon mafia", "unregistered magic", "spicy nostalgia",
  "a rental personality", "the church of snacks", "a haunted lawn chair", "backup emotions",
  "the goblin market", "a suspicious amount of mayonnaise", "off-season Santa", "moon jerky",
  "the underground potluck", "a discount time machine", "grandpa's secret sauce",
  "an emotional support raccoon", "the sock goblin", "spare thunder", "a haunted fax machine",
  "the mailman's secret life", "a rental apocalypse", "damp irony", "the last good sandwich",
  "a suspicious hug", "off-brand destiny", "the neighborhood cryptid council",
  "a two-week-old prophecy", "gravy-based diplomacy", "the raccoon's day off",
  "a discount guardian angel", "spicy paperwork", "the ghost of last Thanksgiving",
  "a haunted parking spot", "backup grandmas", "the sock drawer conspiracy",
  "a rental thunderstorm", "moist paperwork", "the goblin's day job", "spare mustaches",
  "a suspiciously polite squirrel", "off-season werewolves", "the mayor's secret jerky stash",
  "a haunted glove compartment", "damp confidence", "the last known spoon",
  "a discount exorcism", "spicy small talk", "the neighborhood's ghost intern",
  "a rental prophecy", "backup thunder god", "the raccoon's union meeting",
  "a suspicious casserole", "off-brand karma", "the goblin's tax return",
  "a haunted vending machine", "moist diplomacy", "the last unicorn's lawyer",
  "a discount soulmate hotline", "spicy grandma energy", "the neighborhood cryptid potluck",
  "a rental mustache emergency", "backup goblins", "the sock puppet parliament",
  "a suspicious number of raccoons", "off-season thunder", "the mayor's ghost cousin",
  "a haunted lawn gnome", "damp nostalgia", "the last known casserole",
  "a discount time-traveling grandma", "spicy paperwork emergency", "the neighborhood's secret goblin",
  "a rental apocalypse coupon", "backup mystery meat", "the raccoon's secret diary",
  "a suspicious séance invitation", "off-brand thunder god", "the goblin's day planner",
  "a haunted fanny pack emergency", "moist irony", "the last good grandma joke",
  "a discount cryptid sighting", "spicy small talk energy", "the neighborhood's ghost potluck",
  "a rental prophecy refund", "backup thunder cousins", "the sock drawer parliament",
  "a suspicious raccoon union", "off-season karma", "the mayor's secret casserole",
  "a haunted vending machine curse", "damp diplomacy energy", "the last unicorn's day job",
  "a discount soulmate refund", "spicy grandma paperwork", "the neighborhood cryptid emergency",
  "a rental mustache refund", "backup goblin cousins", "the sock puppet emergency",
  "a suspicious number of thunder gods", "off-brand karma refund", "the mayor's ghost jerky",
  "a haunted lawn gnome union", "damp nostalgia refund", "the last known casserole emergency",
  "a discount time-traveling raccoon", "spicy paperwork refund", "the neighborhood's secret potluck",
  "a rental apocalypse emergency", "backup mystery casserole", "the raccoon's secret union",
  "a suspicious séance refund", "off-brand thunder cousin", "the goblin's tax emergency",
  "expired mall wizardry", "the food court's secret cult", "a haunted parking garage",
  "grandpa's other truck", "a suspicious amount of confetti", "the town's backup mayor",
  "damp bravado", "a discount fortune teller's assistant", "the neighborhood's ghost accountant",
  "a rental thunder cape", "spicy elevator music", "the raccoon's retirement plan",
  "a haunted gym membership", "off-brand bravery", "the goblin's carpool lane",
  "moist small talk", "the last known handshake", "a discount séance discount",
  "spicy grandma's secret potluck", "the neighborhood's cryptid carpool", "a suspicious glove compartment",
  "backup thunder etiquette", "the sock goblin's day off", "a haunted casserole dish",
  "off-season mayonnaise", "the mailman's secret cult", "a rental soulmate refund",
  "damp bravado energy", "the last unicorn's tax return", "a discount time-traveling mailman",
  "spicy elevator diplomacy", "the raccoon's secret potluck union", "a haunted fanny pack refund",
  "backup mystery mayo", "the goblin's retirement casserole", "a suspicious thunder cape",
  "off-brand séance etiquette", "the neighborhood's ghost carpool", "a rental werewolf discount",
  "moist bravado", "the last known thunder god", "a discount cryptid retirement plan",
  "spicy grandma's tax return", "the sock puppet's secret cult", "a haunted mailbox curse",
  "backup goblin etiquette", "the mayor's secret elevator music", "a suspicious raccoon refund",
  "off-season bravery", "the neighborhood's ghost mustache", "a rental time-traveling potluck",
  "damp mayonnaise diplomacy", "the last good thunder cape", "a discount séance carpool",
  "spicy elevator bravado", "the goblin's secret parking spot", "a haunted casserole refund",
  "backup thunder cousins union", "the raccoon's tax etiquette", "a suspicious mailbox cult",
  "off-brand mustache retirement", "the neighborhood's cryptid discount", "a rental ghost accountant",
  "moist elevator diplomacy", "the last known séance refund", "a discount werewolf etiquette",
  "spicy potluck retirement plan", "the sock goblin's tax cousin", "a haunted mustache union",
  "backup casserole discount", "the mayor's secret carpool cult", "a suspicious thunder etiquette",
  "off-season séance bravado", "the neighborhood's ghost mayo", "a rental cryptid discount refund",
  "damp elevator etiquette", "the last unicorn's carpool lane", "a discount thunder cousin retirement",
  "spicy mailbox diplomacy", "the raccoon's secret casserole cult", "a haunted potluck etiquette",
  "backup mustache bravado", "the goblin's tax carpool refund", "a suspicious séance discount cousin",
  "off-brand werewolf mayo", "the neighborhood's ghost etiquette union", "a rental thunder mailbox",
  "moist casserole bravado", "the last known mustache refund", "a discount potluck cult",
  "spicy carpool retirement", "the sock puppet's secret mayo", "a haunted elevator discount",
  "the deep-fried apology tour", "a suspicious number of participation trophies",
  "grandma's illegal chili recipe", "the DMV's secret handshake", "a rental jury duty excuse",
  "off-brand small talk about the weather", "the last known parking validation",
  "a haunted HOA meeting", "damp small talk about the economy", "the discount airport shuttle prophecy",
  "a suspicious amount of loyalty points", "backup small talk about traffic",
  "the neighborhood's secret carpool lane cult", "a rental gym membership curse",
  "spicy jury duty energy", "the goblin's DMV appointment", "off-season loyalty program",
  "a haunted airport shuttle", "moist small talk about parking", "the last good jury summons",
  "a discount HOA newsletter", "backup small talk about gas prices", "the raccoon's parking validation",
  "a suspicious gym membership refund", "off-brand jury duty excuse", "the neighborhood's HOA cult",
  "damp small talk about traffic patterns", "a rental participation trophy",
  "spicy DMV small talk", "the goblin's loyalty program discount", "a haunted parking validation refund",
  "backup jury duty etiquette", "the last known airport shuttle cult", "off-season HOA bravado",
  "a discount gym membership union", "moist traffic diplomacy", "the sock goblin's jury summons",
  "a suspicious loyalty point refund", "backup small talk about the mail",
  "the neighborhood's parking validation cousin", "a rental HOA newsletter cult",
  "spicy gym membership etiquette", "off-brand airport shuttle bravado", "the goblin's traffic patterns",
  "a haunted loyalty program refund", "damp jury duty bravado", "the last known HOA cult refund",
  "a discount parking validation cousin", "backup gym membership discount", "moist small talk cult",
  "the raccoon's airport shuttle retirement", "a suspicious traffic pattern union",
  "off-season parking validation bravado", "the neighborhood's small talk cousin"
];
export const HAND_SIZE = 5;
